// Bundles the plugin into one file so it ships as a single payload asset with a stable
// digest. ESM importing nothing but node: builtins, which is what OpenCode's loader expects.
import { build } from "esbuild"
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

// Anchored to this file, not the shell's working directory, so the build works from anywhere.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const outfile = path.join(root, "dist/armor1-opencode.js")

const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"))

await build({
  entryPoints: [path.join(root, "src/index.ts")],
  outfile,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  minify: true,
  external: ["node:*"],
  legalComments: "none",
  banner: {
    js: `// Armor1 OpenCode policy plugin v${pkg.version}. Generated by scripts/build.mjs, do not edit.`,
  },
})

const bytes = readFileSync(outfile)
writeFileSync(`${outfile}.sha256`, `${createHash("sha256").update(bytes).digest("hex")}\n`)
console.log(`built ${path.relative(root, outfile)} (${bytes.length} bytes)`)
